/* SPDX-License-Identifier: GPL-2.0 */
/*
 * HMB trace ring buffer ABI — user-space mirror.
 *
 * Byte-for-byte mirror of kernel/module/hmb_ring.h. Do NOT edit this file
 * directly; edit the kernel copy and re-mirror in the same commit that
 * bumps HMB_TRACE_ABI_VERSION and updates docs/trace-format.md.
 */
#ifndef HMB_TRACE_RING_H
#define HMB_TRACE_RING_H

#include <stdint.h>

#define HMB_TRACE_MAGIC          0x54424d48u  /* "HMBT" little-endian */
#define HMB_RECORD_MAGIC         0x54434552u  /* "RECT" little-endian */
#define HMB_TRACE_ABI_VERSION    1u
#define HMB_RECORD_HDR_SIZE      32u
#define HMB_RECORD_ALIGN         8u

#define HMB_RING_FLAG_OVERFLOWED (1u << 0)
#define HMB_RING_FLAG_FROZEN     (1u << 1)

#define HMB_REC_FLAG_WRAP_MARKER (1u << 0)
#define HMB_REC_FLAG_TRUNCATED   (1u << 1)

struct hmb_ring_hdr {
	uint32_t magic;
	uint32_t version;
	uint32_t ring_size;
	uint32_t record_area_off;
	uint64_t head;
	uint64_t tail;
	uint32_t flags;
	uint32_t reserved0;
	uint64_t reserved1;
	uint64_t reserved2;
	uint64_t reserved3;
} __attribute__((packed));

struct hmb_record_hdr {
	uint32_t magic;
	uint32_t seq;
	uint64_t ts_ns;
	uint16_t opcode;
	uint8_t  cpu;
	uint8_t  flags;
	uint16_t payload_len;
	uint16_t reserved0;
	uint64_t reserved1;
} __attribute__((packed));

_Static_assert(sizeof(struct hmb_ring_hdr) == 64, "hmb_ring_hdr must be 64 bytes");
_Static_assert(sizeof(struct hmb_record_hdr) == 32, "hmb_record_hdr must be 32 bytes");

#endif /* HMB_TRACE_RING_H */
